services:
  - type: web
    name: connecthub
    env: python
    buildCommand: |
      pip install -r requirements_render.txt
      python -c "import nltk; nltk.download('punkt')"
    startCommand: gunicorn microblog:app --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: connecthub_db
          property: connectionString
    plan: free

databases:
  - name: connecthub_db
    plan: free