services:
  - type: web
    name: tinybook
    env: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: gunicorn --workers=1 --threads=2 --timeout=120 microblog:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 1
      - key: WORKER_CLASS
        value: sync
    plan: free

buildCommand: |
  pip install -r requirements_render.txt
  python add_read_column.py